---
title: Minty
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: ''
  uploads:
    title: Uploads
    output: true
  projects:
    title: Work
    output: true
    description: ''
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/placeholder-social.png"
    is_center: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/placeholder-social.png"
- scope:
    path: ''
    type: projects
  values:
    layout: project
    image: "/assets/placeholder-social.png"
exclude:
- README.md
- CNAME
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: MintyMoGraph
author: MintyMoGraph
social:
  name: Stephen Minty
  links:
  - https://twitter.com/MintyMoGraph
  - http://uk.linkedin.com/in/stephenminty
  - http://vimeo.com/itsminty
  - https://www.instagram.com/stephenminty/
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "/assets/logo.jpg"
description: The portfolio website of Stephen Minty, a motion designer and animation
  director based in Bristol.
url: https://itsminty.co.uk
repo: https://github.com/daviddarnes/itsminty.co.uk
email: info@itsminty.co.uk
avatarurl: https://cdn.dribbble.com/users/936341/avatars/small/3fbe67b2e6e052febc21d54d5254a9bb.jpg
navigation_header:
  Work: "/#work"
  About: "/#profile"
  Contact: "/#contact"
  Blog: "/blog/"
social_links:
  Twitter: https://twitter.com/MintyMoGraph
  Instagram: https://www.instagram.com/stephenminty/
  Dribbble: http://www.dribbble.com/mintymograph
  Vimeo: http://vimeo.com/itsminty
  LinkedIn: http://uk.linkedin.com/in/stephenminty
sharing_links: 
